function model = sgplvmSetLatentDimension(model,type,dim,verbose)

% SGPLVMSETLATENTDIMENSION Specify latent dimension type
% FORMAT
% DESC Takes a sgplvm model and specifies latent dimension
% type/constraint
% ARG model : sgplvm model
% ARG type : type of dimension (gen or back)
% ARG dim : dimension
% ARG verbose :
% RETURN model : modified sgplvm model
%
% SEEALSO : sgplvmCreate
%
% COPYRIGHT : Neil D. Lawrence, Carl Henrik Ek, 2008

% SGPLVM

if(nargin<4)
  verbose = false;
  if(nargin<3)
    error('Too Few Arguments');
  end
end

switch type
 case 'back'
  model.back.indexOut = dim;
  if(verbose)
    fprintf('Model back-constrains dimension:\t%d\n',dim);
  end
 case 'gen'
  for(i = 1:1:length(model.kern.comp))
    model.kern.comp{i}.index = dim;
  end
  if(verbose)
    fprintf('Model observations generated by dimension:\t%d\n',dim);
  end
 otherwise
  error('Undefined type, only "gen" and "back" defined');
end